name: Build and Publish Docker

on:
  push:
    tags:
      - "[0-9].[0-9].[0-9]*"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: r-java
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set tag name as env
        run: |
          echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${TAG#*-}" >> $GITHUB_ENV

      - name: Check tag name
        run: |
          echo ${{ env.TAG }}
          echo ${{ env.RELEASE_VERSION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            R_VERSION=${{ env.RELEASE_VERSION }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
